import { ViewListIcon } from "@heroicons/react/solid";

const obj = {
  title: "Workout Plan",
  desc:
    "A workout plan is a schedule of exercises and activities to improve physical fitness or achieve specific health or fitness goals over a set period of time.",
  additionalSystemTextForChatBot:
    "You are an AI assistant that is an expert with Workout/Health/Nutrition Plans. You know about everything related to the above Travel Plan and things that are related to the above plan. You can provide advice related to the above Workout Plan. If someone is asking anything which is outside workout/health related query than please respond with the phrase \"I'm just  your Workout assistant. I can't help with that.\"",
  category: "Personal",
  Icon: ViewListIcon,
  permissions: ["user"],
  isRecommendationsAvailable: true,

  subsequentQuestion: "/ai/subsequentQuestion",
  fromColor: "green-500",
  toColor: "blue-500",

  to: "/workout",
  api: "/free/workout",

  output: {
    title: "Workout plan",
    desc: "The following key points detected",
    Icon: false,
    color: "blue",
  },

  prompts: [
    {
      title: "Entry Text",
      desc:
        "A sentence or paragraph you wish to understand in bullet point form.",
      // n: 1,
      prompts: [
        {
          title: "Age",
          attr: "age",
          value: "",
          placeholder: "Age",
          //   label: "Examples: Udaipur, Shimla, Nanital",
          // type: "textarea",
          maxLength: 20,
          // max: 100,
          min: 1,
          required: true,
          error: "",
        },
        {
          title: "Gender",
          attr: "gender",
          value: "",
          placeholder: "Gender",
          // label: "Examples: 2,5",
          //type: "number",
          maxLength: 20,
          // max: 100,
          min: 1,
          required: true,
          error: "",
          example: "5",
        },
        {
          title: "Height",
          attr: "height",
          value: "",
          placeholder: "Height",
          //label: "Examples: 2,5",
          //type: "number",
          maxLength: 20,
          // max: 100,
          min: 1,
          required: true,
          error: "",
          example: "5",
        },
        {
          title: "Weight",
          attr: "weight",
          value: "",
          placeholder: "Weight",
          // label: "Examples: 2,5",
          //   type: "number",
          maxLength: 20,
          // max: 100,
          min: 1,
          required: true,
          error: "",
          example: "5",
        },
        {
          title: "Fitness Goal",
          attr: "fitnessGoal",
          value: "",
          placeholder: "Fitness Goal",
          label: "Weight loss, muscle building, overall fitness",
          //type: "number",
          maxLength: 40,
          // max: 100,
          min: 1,
          required: true,
          error: "",
          example: "5",
        },
        {
          title: "Schedule Availability or Days/Week",
          attr: "scheduleAvailability",
          value: "",
          placeholder: "Schedule Availability or Days/Week",
          label: "3,4,5",
          //type: "number",
          maxLength: 40,
          // max: 100,
          min: 1,
          required: true,
          error: "",
          example: "5",
        },
        {
          title: "Health Information",
          attr: "healthInformation",
          value: "",
          placeholder: "Health Information",
          label: "Health conditions, injuries, or medical restrictions",
          //type: "number",
          maxLength: 40,
          // max: 100,
          min: 1,
          required: true,
          error: "",
          example: "5",
        },
      ],
      example: {
        output:
          "Hello World Hello World Hello World Hello World Hello World Hello World Hello World ",
        // outputs: [
        // 	"The sun is very old, over 4.5 billion years",
        // 	"At 10,000 degrees, sun is also very hot",
        // 	"Gasses called coronal mass ejections erupt from the sun",
        // ],
        // Icon: RefreshIcon,
        color: "blue",
      },
    },
  ],
};

export default obj;
