import { ViewListIcon } from "@heroicons/react/solid";

const obj = {
  title: "Meal Plan",
  desc: "A meal plan outlines the types and quantities of food to be consumed over a specific period of time, often with the goal of achieving a specific health or fitness goal.",
  category: "Personal",
  Icon: ViewListIcon,
  // tags: [],
  permissions: ["user"],

  fromColor: "green-500",
  toColor: "blue-500",

  to: "/ai/mealplan",
  api: "/ai/mealplan",
  isRecommendationsAvailable: false,

  output: {
    title: "Meal Plan",
    desc: "The following key points detected",
    Icon: false,
    color: "blue",
  },

  prompts: [
    {
      title: "Entry Text",
      desc: "A sentence or paragraph you wish to understand in bullet point form.",
      // n: 1,
      prompts: [
        {
          title: "Target Caloric Intake",
          attr: "targetCaloricIntake",
          value: "",
          placeholder: "Target Caloric Intake",
          //   label: "Examples: Udaipur, Shimla, Nanital",
          // type: "textarea",
          label: "1500, 2000, 2500 etc",
          maxLength: 40,
          // max: 100,
          min: 1,
          required: true,
          error: "",
        },
        {
          title: "Food Preferences",
          attr: "foodPreferences",
          value: "",
          placeholder: "Food Preferences",
          //   label: "Examples: Udaipur, Shimla, Nanital",
          // type: "textarea",
          maxLength: 20,
          label: "Veg, Non Veg or Both",
          // max: 100,
          min: 1,
          required: true,
          error: "",
        },
        {
          title: "Physical Activity Level",
          attr: "physicalActivityLevel",
          value: "",
          placeholder: "Physical Activity Level",
          // label: "Examples: 2,5",
          //type: "number",
          maxLength: 20,
          // max: 100,
          min: 1,
          required: true,
          error: "",
          example: "5",
          label: "High, Medium, Low",
        },
        {
          title: "Health Conditions",
          attr: "healthConditions",
          value: "",
          placeholder: "Health Conditions",
          //label: "Examples: 2,5",
          //type: "number",
          maxLength: 20,
          // max: 100,
          min: 1,
          required: true,
          error: "",
          example: "5",
          label: "Health conditions, injuries, or medical restrictions",
        },
        {
          title: "Daily Meal Frequency",
          attr: "mealFrequencyAndTiming",
          value: "",
          placeholder: "Meal Frequency",
          // label: "Examples: 2,5",
          //   type: "number",
          maxLength: 20,
          // max: 100,
          min: 1,
          required: true,
          error: "",
          example: "5",
          label: "3, 4 and 5",
        },
        {
          title: "Monthly Meal Budget",
          attr: "mealBudget",
          value: "",
          placeholder: "Monthly Meal Budget",
          // label: "Examples: 2,5",
          //   type: "number",
          maxLength: 20,
          // max: 100,
          min: 1,
          required: true,
          error: "",
          example: "5",
          label: "E.g INR 20,000",
        },
        {
          title: "Cooking Skills",
          attr: "cookingSkills",
          value: "",
          placeholder: "Cooking Skills",
          // label: "Examples: 2,5",
          //   type: "number",
          maxLength: 20,
          // max: 100,
          min: 1,
          required: true,
          error: "",
          example: "5",
          label: "No Experience, Beginner, Expert",
        },
        {
          title: "Cooking Equipment Available",
          attr: "equipmentAvailable",
          value: "",
          placeholder: "Cooking Equipment Available",
          // label: "Examples: 2,5",
          //   type: "number",
          maxLength: 20,
          // max: 100,
          min: 1,
          required: true,
          error: "",
          example: "5",
          label: "Yes or No",
        },
        {
          title: "Cuisine",
          attr: "cuisine",
          value: "",
          placeholder: "Cuisine",
          // label: "Examples: 2,5",
          //   type: "number",
          maxLength: 20,
          // max: 100,
          min: 1,
          required: true,
          error: "",
          label: "Indian, Continental, American etc.",
        },
      ],
      example: {
        // output: "",
        outputs: [
          "The sun is very old, over 4.5 billion years",
          "At 10,000 degrees, sun is also very hot",
          "Gasses called coronal mass ejections erupt from the sun",
        ],
        // Icon: RefreshIcon,
        color: "blue",
      },
    },
  ],
};

export default obj;
