import { MenuAlt2Icon } from "@heroicons/react/solid";

const obj = {
  title: "SEO Plan",
  desc: "An SEO plan outlines the strategies and actions needed to improve the visibility and ranking of a website in search engine results.",
  category: "Professional",
  Icon: MenuAlt2Icon,
  // tags: [],
  permissions: ["user"],

  fromColor: "yellow-400",
  toColor: "yellow-600",

  to: "/ai/seo",
  api: "/ai/seo",

  output: {
    title: "Introduction",
    desc: "The following introduction has been generated",
    // Icon: RefreshIcon,
    // color: "",
  },

  prompts: [
    {
      title: "Entry Text",
      desc: "Write small sentence or paragraph you wish to review.",
      // n: 1,
      prompts: [
        {
          title: "Domain Name",
          attr: "domainName",
          value: "",
          placeholder: "Domain Name",
          //   label: "Examples: Udaipur, Shimla, Nanital",
          type: "textarea",
          maxLength: 200,
          // max: 100,
          min: 1,
          required: true,
          error: "",
        },
        {
          title: "Target Audience Demographics",
          attr: "targetAudienceDemographics",
          value: "",
          placeholder: "Target Audience Demographics",
          //   label: "Examples: Udaipur, Shimla, Nanital",
          type: "textarea",
          maxLength: 200,
          // max: 100,
          min: 1,
          required: true,
          error: "",
        },
        {
          title: "Target Audience Interests",
          attr: "targetAudienceInterests",
          value: "",
          placeholder: "Target Audience Interests",
          //   label: "Examples: Udaipur, Shimla, Nanital",
          type: "textarea",
          maxLength: 200,
          // max: 100,
          min: 1,
          required: true,
          error: "",
        },
        {
          title: "Target Audience Behaviors",
          attr: "targetAudienceBehaviors",
          value: "",
          placeholder: "Target Audience Behaviors",
          //   label: "Examples: Udaipur, Shimla, Nanital",
          type: "textarea",
          maxLength: 200,
          // max: 100,
          min: 1,
          required: true,
          error: "",
        },
        {
          title: "Keywords",
          attr: "keywords",
          value: "",
          placeholder: "Keywords",
          //   label: "Examples: Udaipur, Shimla, Nanital",
          type: "textarea",
          maxLength: 200,
          // max: 100,
          min: 1,
          required: true,
          error: "",
        },
        {
          title: "Business Goals",
          attr: "businessGoals",
          value: "",
          placeholder: "Business Goals",
          //   label: "Examples: Udaipur, Shimla, Nanital",
          type: "textarea",
          maxLength: 200,
          // max: 100,
          min: 1,
          required: true,
          error: "",
        },
        {
          title: "Competitor Analysis",
          attr: "competitorAnalysis",
          value: "",
          placeholder: "Competitor Analysis",
          //   label: "Examples: Udaipur, Shimla, Nanital",
          type: "textarea",
          maxLength: 200,
          // max: 100,
          min: 1,
          required: true,
          error: "",
        },
        {
          title: "Budget and Timeline",
          attr: "budgetAndTimeline",
          value: "",
          placeholder: "Budget and Timeline",
          //   label: "Examples: Udaipur, Shimla, Nanital",
          type: "textarea",
          maxLength: 200,
          // max: 100,
          min: 1,
          required: true,
          error: "",
        },
      ],
      example: {
        output:
          "Storybook is a development environment for UI components. It helps you iterate faster on UI code. It allows you to browse a component library, view the different states of each component, and interactively develop and test components.\n\nI believe in Storybook’s value, and I’m sure it will improve your workflow. But I’m also going to share with you a different approach that can help you save some time without using a JavaScript framework.",
        // outputs: [],
        // Icon: RefreshIcon,
        // color: "",
      },
    },
  ],
};

export default obj;
