import { ViewListIcon } from "@heroicons/react/solid";

const obj = {
  title: "Travel Plan",
  desc: "A travel plan outlines the details of a trip, including destinations, accommodation, transportation, and activities.",
  category: "Personal",
  Icon: ViewListIcon,
  // tags: [],
  permissions: ["user"],
  isRecommendationsAvailable: true,

  fromColor: "gray-500",
  toColor: "gray-500",

  to: "/ai/travel",
  api: "/ai/travel",
  subsequentQuestion: "/ai/subsequentQuestion",

  output: {
    title: "Travel",
    desc: "The following key points detected",
    Icon: false,
    color: "blue",
  },

  prompts: [
    {
      title: "Entry Text",
      desc: "A sentence or paragraph you wish to understand in bullet point form.",
      // prompts: [
      //   {
      //     title: "Destination",
      //     attr: "destination",
      //     value: "",
      //     placeholder: "",
      //     maxLength: 20,
      //     error: "",
      //     min: 1,
      //     required: true,
      //     // type: "number",
      //     // max: 100,
      //     // example: "5",
      //     // label: "Examples: 2,5",
      //   }
      // ],
      prompts: [
        // {
        //   title: "Destination",
        //   attr: "destination",
        //   value: "",
        //   type: "text",
        //   // options: [
        //   //   { title: "Mumbai", value: "Mumbai", label: "Mumbai" },
        //   //   { title: "Delhi", value: "Delhi", label: "Delhi" },
        //   //   { title: "Bangalore", value: "Bangalore", label: "Bangalore" },
        //   // ],
        //   placeholder: "Select City",
        //   required: true,
        //   error: "", // label: "Examples: Udaipur, Shimla, Nanital",
        //   // maxLength: 40,
        //   // // max: 100,
        //   // min: 1,
        //   // label: "Examples: Udaipur, Shimla, Nanital",
        //   // type: "textarea",
        //   // maxLength: 40,
        //   // max: 100,
        //   // min: 1,
        //   // example: "Udaipur",
        // },
        {
          title: "Source",
          attr: "source",
          value: "",
          placeholder: "",
          maxLength: 80,
          error: "",
          min: 1,
          required: true,
        },
        {
          title: "Destination",
          attr: "destination",
          value: "",
          placeholder: "",
          maxLength: 80,
          error: "",
          min: 1,
          required: true,
        },
        {
          title: "Purpose",
          attr: "purpose",
          value: "",
          placeholder: "",
          maxLength: 80,
          error: "",
          min: 1,
          required: true,
        },
        {
          title: "Date",
          attr: "date",
          value: "",
          type: "dateRange",
          required: true,
          error: "",
        },
        {
          title: "Budget",
          attr: "budget",
          value: "",
          placeholder: "INR: 50,000",
          maxLength: 20,
          error: "",
          min: 1,
          required: true,
        },
        {
          title: "Travellers",
          attr: "traveller",
          value: "",
          type: "radiogroup",
          required: true,
          error: "",
          options: [
            {
              label: "Solo",
            },
            {
              label: "Couple",
            },
            {
              label: "Family",
            },
            {
              label: "Friends",
            },
          ],
        },
        {
          title: "Accomodation",
          attr: "accomodation",
          value: "",
          type: "dropdown",
          options: [
            { title: "Hotel", value: "Hotel", label: "Hotel" },
            { title: "Hostel", value: "Hostel", label: "Hostel" },
            { title: "AirBnb", value: "AirBnb", label: "AirBnb" },
          ],
          placeholder: "Select Accomodation",
          required: true,
          error: "", // label: "Examples: Udaipur, Shimla, Nanital",
          // maxLength: 40,
          // // max: 100,
          // min: 1,
          // label: "Examples: Udaipur, Shimla, Nanital",
          // type: "textarea",
          // maxLength: 40,
          // max: 100,
          // min: 1,
          // example: "Udaipur",
        },
        {
          title: "Transportation",
          attr: "transportation",
          value: "",
          type: "dropdown",
          options: [
            { title: "Flight", value: "Flight", label: "Flight" },
            { title: "Train", value: "Train", label: "Train" },
            { title: "Bus", value: "Bus", label: "Bus" },
            { title: "Car", value: "Car", label: "Car" },
            { title: "Bike", value: "Bike", label: "Bike" },
          ],
          placeholder: "Select Transportation",
          required: true,
          error: "", // label: "Examples: Udaipur, Shimla, Nanital",
          // maxLength: 40,
          // // max: 100,
          // min: 1,
          // label: "Examples: Udaipur, Shimla, Nanital",
          // type: "textarea",
          // maxLength: 40,
          // max: 100,
          // min: 1,
          // example: "Udaipur",
        },
        {
          title: "Meal Preference",
          attr: "meal_Preference",
          value: "",
          type: "radiogroup",
          required: true,
          error: "",
          options: [
            {
              label: "Veg",
            },
            {
              label: "Non Veg",
            },
            {
              label: "Both",
            },
          ],
        },
        {
          title: "Any Health or Safety Concerns",
          attr: "Any_Health_or_Safety_Concerns",
          value: "",
          placeholder: "",
          maxLength: 20,
          error: "",
          min: 1,
          required: true,
          // type: "number",
          // max: 100,
          // example: "5",
          // label: "Examples: 2,5",
        },
        {
          title: "Travel Style",
          attr: "travelStyle",
          value: "",
          type: "dropdown",
          options: [
            { title: "Luxury", value: "Luxury", label: "Luxury" },
            { title: "Budget", value: "Budget", label: "Budget" },
            { title: "Group Tour", value: "Group Tour", label: "Group Tour" },
          ],
          placeholder: "Select Travel Type",
          required: true,
          error: "", // label: "Examples: Udaipur, Shimla, Nanital",
          // maxLength: 40,
          // // max: 100,
          // min: 1,
          // label: "Examples: Udaipur, Shimla, Nanital",
          // type: "textarea",
          // maxLength: 40,
          // max: 100,
          // min: 1,
          // example: "Udaipur",
        },
        {
          title: "Additional Info",
          attr: "additionalinfo",
          value: "",
          type: "multipleCheckbox",
          // max: 100,
          required: true,
          error: "",
          example: "5",
          options: [
            {
              label: "Best Place to eat",
            },
            {
              label: "Things to do",
            },
            {
              label: "Travel tips",
            },
          ],
        },
      ],
      example: {
        output:
          "Hello World Hello World Hello World Hello World Hello World Hello World Hello World ",
        // outputs: [
        // 	"The sun is very old, over 4.5 billion years",
        // 	"At 10,000 degrees, sun is also very hot",
        // 	"Gasses called coronal mass ejections erupt from the sun",
        // ],
        // Icon: RefreshIcon,
        color: "blue",
      },
    },
  ],
};

export default obj;
